# Generated by Django 4.2.8 on 2023-12-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='@a.com', max_length=254, unique=True)),
                ('nickname', models.CharField(default='none', max_length=30)),
                ('password', models.CharField(default='111', max_length=128)),
                ('likeWords', models.ManyToManyField(blank=True, related_name='users', to='word.word')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
