# Generated by Django 4.2.7 on 2023-12-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likeWords',
            field=models.ManyToManyField(related_name='liked_by_users', to='word.word'),
        ),
    ]
