# Generated by Django 4.2.7 on 2023-12-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizId', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('questions', models.ManyToManyField(related_name='quizzes', to='question.question')),
            ],
        ),
    ]
